services:
  - type: web
    name: frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    headers:
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.mjs
        name: Content-Type
        value: application/javascript
      - path: /*.css
        name: Content-Type
        value: text/css
